---
blacklist:
  - GPL-2.0

whitelist:
  - Apache-2.0
  - 0BSD
  - BSD
  - FreeBSD
  - CC
  - ISC
  - MIT
  - MPL-2.0
  - NewBSD
  - BSD-3-Clause
  - BSD-2-Clause
  - MPL-2.0-no-copyleft-exception
  - BSD-Protection
  - BSD-1-Clause
  - BSD-4-Clause

exceptions:
  - github.com/davecgh/go-spew/spew/...
  - github.com/dchest/uniuri
  - github.com/opencontainers/go-digest
  - github.com/certifi/gocertifi
  - github.com/AndreasBriese/bbloom
  - github.com/prometheus/common/...
  - github.com/magiconair/properties/...
  - github.com/dgraph-io/badger/...
  - github.com/tetratelabs/protoc-gen-cobra/...
  - github.com/gogo/protobuf/...
  - sigs.k8s.io/yaml/... #MIT
  - github.com/marten-seemann/chacha20/...
  - github.com/kr/session/...
